### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by RobbieVerdurme** [RobbieVerdurme/menuapp_pwa#2]
### Description
get all the data from google firebase
use the nuxt plugin for that
link : https://firebase.nuxtjs.org/

### Update
[Update 2020-03-24]
link to implement firebase
- https://www.youtube.com/watch?v=ix22-aX69qo
- https://www.youtube.com/watch?v=_-_bz5lH_fI&t=2183s

### TODO
- [x] Add google firebase package
- [x] Configure google firebase
- [x] get data from google firebase
- [x] show data from google firebase
