### ISSUE TITLE
Add menu

### ISSUE THREAD

**Issue by RobbieVerdurme** [RobbieVerdurme/menuapp_pwa#21]
### Description
make the app so you can add a menu if you are on the list page. To add a menu to firebase you need to be logged on

### TODO
- [x] make add page info
- [x] make add page ingredients
- [x] make add page perperation
- [x] make add button menu on listpage
- [x] make add menu to firebase
