### ISSUE TITLE
menupicker

### ISSUE THREAD

**Issue by RobbieVerdurme** [RobbieVerdurme/menuapp_pwa#3]
### Description
make the first page that gives a random list item from the list of menu's

### TODO
- [x] add picker component
- [x] implement picker into first page(index.vue)
- [x] make default store list of menu's
- [x] get a random item from list if list is not empty
- [x] if list empty then return list empty error
