### ISSUE TITLE
Edit menu

### ISSUE THREAD

**Issue by RobbieVerdurme** [RobbieVerdurme/MenuApp_PWA#37]
### Description
Make the menu editable by the person that made it.

### TODO
- [x] add store attribute chosen menu
- [x] add mutations for chosen menu
- [x] if the menu is already in firebase update menu else create menu
- [x] edit register pages
- [x] make sure it works
