### ISSUE TITLE
Swipeable pages

### ISSUE THREAD

**Issue by RobbieVerdurme** [RobbieVerdurme/MenuApp_PWA#42]
### Description
The meaning of this issue is to make the pages swipe able. So you get the native app experience.

### Specialty
There will be a need for a external library to do this
This is a librairy that enables swiping on touch enabled devices
links : 
- https://vuetifyjs.com/en/directives/touch-support/
- https://vuetifyjs.com/en/getting-started/quick-start/
- https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/touch-support/usage.vue

Got the nuxt verison
link : https://github.com/nuxt-community/vuetify-module

### TODO
- [x] find external library to make page swipe able
- [x] install package
- [x] implement touch controls into pages
- [x] make sure it works
