### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by RobbieVerdurme** [RobbieVerdurme/MenuApp_PWA#44]
### Description
Add a register page so new users can register to the site and add menu's

### TODO
- [x] add register page
- [x] register functionality (backendcall to firebase)
- [x] make sure it works
