### ISSUE TITLE
Menulist

### ISSUE THREAD

**Issue by RobbieVerdurme** [RobbieVerdurme/menuapp_pwa#7]
### Description
make a list page to show all the menus on that page. Add a filter to the page so the user can filter on ingredient or name of the menu

### TODO
- [x] make an list molecule page
- [ ] make an filter molecule page
- [x] make bottom navigation work
- [ ] add filter molecule to list page
- [x] add list molecule to list page
