### ISSUE TITLE
Menudetail

### ISSUE THREAD

**Issue by RobbieVerdurme** [RobbieVerdurme/menuapp_pwa#8]
### Description
add a menu detail so the user can see how the menu is made use [tabs](https://vuematerial.io/components/tabs) to switch between pages

### TODO
- [x] Add menu organism page
- [x] add a detail menu molecule page
- [x] add a ingredient menu molecule page
- [x] add a how its made molecule page
- [x] nuxt-link to the menu from the list or generated menu item
